# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Breaking Changes
      labels:
        - breaking-change        
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"