name: Sync ada-version file

on:
  push:
    tags:
      - 'v*'        # run automatically when a tag is pushed
  workflow_dispatch:  # allow manual trigger in Github UI

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # we need full tag history

      - name: Determine version
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            # Get the latest tag from Git
            VERSION=$(git describe --tags --abbrev=0)
          else
            # Use the tag that triggered the workflow
            VERSION="${GITHUB_REF_NAME}"
          fi
          echo "Detected version: ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Write ada-version file
        run: |
          mkdir -p ada/etc
          echo "${VERSION}" > ada/etc/ada-version

      - name: Commit and push ada-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ada/etc/ada-version
          git commit -m "Update ada-version to ${VERSION}" || echo "No changes"
          git push
